### ISSUE TITLE
[FEATURE] Add `[gump id]` for `gumpresponse` `gumpclose`. Add `gumpexists` `ingump` expressions.

### ISSUE THREAD

**Issue by ncskrypt** [UOOutlands/Razor#30]
`gumpclose [gump id/'any']`
`gumpresponse (buttonID) [gump id/'any']`
- Optionally specify `[gump id]` to respond/close a specific gump, otherwise `any` can be assumed.
- Razor's current behavior responds only to frontmost gump, making many tasks frustrating for players:
-- Playing a macro with the wrong gump frontmost can invoke a completely different action players never intended to happen.
-- Boaters have multiple gumps up at all time, is impossible to manage correctly.

`if gumpexists [gump id/'any']`
- Boolean Expression to indicate if you currently have a gump open.
- Optionally specify `[gump id]`, otherwise `any` can be  assumed.
- Provides similar functionality to `waitforgump [gump id/'any'] [timeout]` but as a boolean expression without waiting.

`if ingump ('message to look for') [gump id/'any']`
- Boolean Expression to indicate if a message is in a gump.
- Optionally specify `[gump id]`, otherwise `any` can be  assumed.
- Provides similar functionality to `insysmsg ('message to look for')` but for gumps
- Razor currently lacks this feature, making many quality of life tasks impossible:
-- Finding a specific guild member by name on `[bossresults` to add to Loot Distro, can take upwards of 10 mins if you have to scroll back several days and search manually.
-- Activating a specific Aspect suit/book/weapon, is impossible to know which Aspect the gump is on.
-- Using any gump that is paginated / changes its content, thus `buttonID`'s will be non-unique and impossible to invoke the correct action without knowing something about the page content.

**Gump Exists (Steam Documentation)**
![image](https://user-images.githubusercontent.com/1661863/125785586-796bbd8f-d5da-468b-b5e9-83ffc82fdd0d.png)

**In Gump (Steam Documentation)**
![image](https://user-images.githubusercontent.com/1661863/125785620-7ce47fbc-5465-45ae-b17f-fac9af983273.png)

**Comment by anethus** [comment]
merged to outlands
