### ISSUE TITLE
[BUG] `@setvar!` local var only for current scope conflicts with `@` quiet mode

### ISSUE THREAD

**Issue by ncskrypt** [UOOutlands/Razor#37]
> Further, to define a purely local variable only for the current scope, use the @ operator in conjunction with the ! operator:
> `@setvar! my_name 0x123`

Need to use a different symbol to invoke the "define a purely local for the current scope"
`@` is already used for quiet mode.

**Comment by jaedan** [comment]
I abused this because the parser could already handle it. I'm going to instead change this so that `@` means quiet again and there's no way to create a "local" variable. It's possible to get the local variable behavior by simply calling unsetvar at the end of the script.
