### ISSUE TITLE
[BUG] `foreach x in list` does not work properly for current item in list

### ISSUE THREAD

**Issue by ncskrypt** [UOOutlands/Razor#38]
`foreach x in list` does not work correctly
- Attempting to push `x` item onto another list simply doesn't work.
- Also is ambiguous as to whether I want to push the current loop item (stored as `var x`) or if I want to push the actual string/word `"x"` onto the list. This ambiguity would be removed if the syntax used something like `x[]` or `list[]`

```as
removelist LIST1
createlist LIST1
pushlist!  LIST1 'some'
pushlist!  LIST1 'thing'

if list LIST1 > 0
  removelist LIST2
  createlist LIST2
  foreach x_in_list1 in LIST1
    overhead x_in_list1       // prints "some" & "thing"
    pushlist LIST2 x_in_list1 // pushes "x_in_list1" into LIST2 twice
  endfor

  if list LIST2 > 0
    foreach x_in_list2 in LIST2
      overhead x_in_list2 // prints "x_in_list1" twice
    endfor
  endif
endif
```

**Comment by jaedan** [comment]
One good fix is to always interpret quoted values as strings rather than variables. Also it seems that pushlist isn't doing variable resolution.

**Comment by jaedan** [comment]
I've fixed the issue with pushlist not resolving the foreach variable. We can file a separate issue for dealing with the ambiguity between strings and variable names.
