### ISSUE TITLE
[BUG] Cannot `setvar 'text'`, throws error

### ISSUE THREAD

**Issue by ncskrypt** [UOOutlands/Razor#55]
`setvar` throws an error if you try to set it to plain text.

**Comment by jaedan** [comment]
Also resolved by 9ba19940bc25e9779c2223003e1424cf9e959026

**Comment by ncskrypt** [comment]
`setvar myvar (text)` casts it as int and expressions fail on it.

![image](https://user-images.githubusercontent.com/1661863/128437246-8823614c-47c2-4e38-9d40-33f95102d826.png)
