### ISSUE TITLE
[BUG] Cant `ignore` mobiles

### ISSUE THREAD

**Issue by ncskrypt** [UOOutlands/Razor#64]
Mobiles can't be ignored with the `ignore` command.

Causes an infinite loop when using `while findtype`
```as
while findtype (some mobile type) 'ground' as 'found'
  ...
   
  ignore 'found' // Does not ignore the object if a mobile
endwhile
```

**Comment by Tranq1** [comment]
Technically the ignore part works - it pushes the serial onto the ignore list. When using findtype to try to find mobiles and it retrieves the list, it just doesn't apply any filtering on it like it does on the item list.

**Comment by anethus** [comment]
https://github.com/UOOutlands/Razor/pull/66
